config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

  resources :restaurantes

   match ':controller(/:action(/:id))(.:format)'
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
   attr_accessible :nome, :idade

  validates_presence_of :nome, message: "deve ser preenchido"
  
  validates_uniqueness_of :nome, message: "nome ja cadastrado"
  
  validates_numericality_of :idade, greater_than: 0,
                                    less_than: 100,
                                    message: "deve ser um numero entre 0 e 100"
  has_many :qualificacoes
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2> Verifique os erros abaixo:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br />
    <%= f.number_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar cliente</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @cliente %> |
<%= link_to 'Voltar', clientes_path %>

app/views/clientes/index.html.erb
<h1>Clientes <a href='/clientes/new' class='btn btn-small pull-right'><i class='icon-plus'></i>Novo Cliente</a></h1>

<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Idade</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.idade %></td>
    <td><%= link_to 'Exibir', cliente %></td>
    <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
	<td><%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
  </tr>
<% end %>
</table>

app/views/clientes/new.html.erb
<h1>Novo cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Idade:</b>
  <%= @cliente.idade %>
</p>

<%= link_to "Nova qualificacao", :controller => "qualificacoes",
								  :action => "new",
								   :cliente => @cliente %> |
<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>