config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

  resources :restaurantes

   match ':controller(/:action(/:id))(.:format)'
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
 respond_to :html, :js
 
 def index
	@restaurantes = Restaurante.order("nome")
	respond_with @restaurante
 end

 def show
   @restaurante = Restaurante.find(params[:id])
   respond_with @restaurante
 end

 def new
   @restaurante = Restaurante.new
   respond_with @restaurante
 end

 def create
   @restaurante = Restaurante.new(params[:restaurante])
   if @restaurante.save
      redirect_to(action: "show", id: @restaurante)
   else
     render action: "new"
   end
 end

 def edit
   @restaurante = Restaurante.find(params[:id])
 end
  
  def update
   @restaurante = Restaurante.find(params[:id])
   if @restaurante.update_attributes(params[:restaurante])
      redirect_to(action: "show", id: @restaurante)
   else
     render action: "edit"
   end
  end
  
  def destroy
    @restaurante = Restaurante.find(params[:id])
    @restaurante.destroy    
	respond_with @restaurante
  end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/edit.html.erb
<%= form_for  @restaurante do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "erros") %>:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	  
    </div>
  <% end %>  
  <legend> Editar Restaurante</legend>
  <label class="control-label">Nome: <%= f.text_field :nome %></label>
  <label class="control-label">Endereco: <%= f.text_field :endereco %></label>
  <label class="control-label">Especialidade: <%= f.text_field :especialidade %></label>
  <%= submit_tag 'Atualizar' %>
	
<% end %>

<%= link_to 'Voltar', action: 'index' %>

app/views/restaurantes/index.html.erb
<a href='/restaurantes/new' class='btn btn-small pull-right'><i class='icon-plus'></i>Novo Restaurante</a>
<legend> Listagem de Restaurantes</legend>
 <table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
	<th>Especialidade</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>
  
<% @restaurantes.each do |restaurante| %>
  <tr>
    <td><%= restaurante.nome %></td>
    <td><%= restaurante.endereco %></td>
    <td><%= restaurante.especialidade %></td>
    <td><%= link_to 'Visualizar', action: 'show', id: restaurante %></td>
    <td><%= link_to 'Editar', edit_restaurante_path(restaurante) %></td>
	<td><%= link_to 'Apagar', restaurante, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
  </tr>
<% end %>
</table>

app/views/restaurantes/new.html.erb
<%= form_for :restaurante, url: {action: 'create'} do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "erros") %>:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	  
    </div>
  <% end %>
  <legend> Adicionando Restaurante</legend>
  <label class="control-label">Nome: <%= f.text_field :nome %></label>
  <label class="control-label">Endereco: <%= f.text_field :endereco %></label>
  <label class="control-label">Especialidade: <%= f.text_field :especialidade %></label>
	<%= submit_tag 'Criar' %>
<% end %>

<%= link_to 'Voltar', {action: 'index' } %>

app/views/restaurantes/show.html.erb
<h1>Restaurante</h1>

  <p>
    <b>Nome: </b>
    <%= @restaurante.nome %>
  </p>

  <p>
    <b>Endereco: </b>
    <%= @restaurante.endereco %>
  </p>

  <p>
    <b>Especialidade: </b>
    <%= @restaurante.especialidade %>
  </p>
  
  <b>Nota media: </b>
  <%= @restaurante.qualificacoes.average(:nota) %><br/>
  <%= @restaurante.qualificacoes.count %><br/>
 
  <b>Preco medio: </b>
  <%= @restaurante.qualificacoes.average(:valor_gasto) %><br/><br/>

  <% unless @restaurante.comentarios.empty?%>
	<%= comentarios @restaurante %>
  <% end %>
  
  <%= novo_comentario(@restaurante) %>
    
  <%= link_to "Qualificar este restaurante", :controller => "qualificacoes",
											  :action => "new",
											  :restaurante => @restaurante %> |
  <%= link_to 'Editar', action: 'edit', id: @restaurante %> |
  <%= link_to 'Voltar', action: 'index' %>