config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

  resources :restaurantes

   match ':controller(/:action(/:id))(.:format)'
end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qualificacoes }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.json
  def new
    @qualificacao = Qualificacao.new

	if params[:cliente]
	   @qualificacao.cliente = Cliente.find(params[:cliente])
	end
	
	if params[:restaurante]
	   @qualificacao.restaurante = Restaurante.find(params[:restaurante])
	end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao criada com sucesso.' }
        format.json { render json: @qualificacao, status: :created, location: @qualificacao }
      else
        format.html { render action: "new" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to @qualificacao, notice: 'Qualificacao atualizada com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to qualificacoes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @qualificacao.cliente %>
	<%= f.hidden_field 'cliente_id' %>
	<% else %>
	  <p><%= f.label :cliente_id %><br />
	<%= f.collection_select(:cliente_id, Cliente.order('nome'),
	                                   :id, :nome, {:prompt => true}) %></p>
  <% end %>
  
  <% if @qualificacao.restaurante %>
	<%= f.hidden_field 'restaurante_id' %>
	<% else %>
	  <p><%= f.label :restaurante_id %><br />
	<%= f.collection_select(:restaurante_id, Restaurante.order('nome'),
	                                       :id, :nome, {:prompt => true}) %></p>
  <% end %>

  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1>Editar qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @qualificacao %> |
<%= link_to 'Voltar', qualificacoes_path %>

app/views/qualificacoes/index.html.erb
<h1>Qualificacoes  <a href='/qualificacoes/new' class='btn btn-small pull-right'><i class='icon-plus'></i>Nova Qualificacao</a></h1>

<table class="table table-striped">
  <tr>
    <th>Cliente</th>
    <th>Restaurante</th>
    <th>Nota</th>
    <th>Valor gasto</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>

<% @qualificacoes.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.restaurante.nome %></td>
    <td><%= qualificacao.nota %></td>
    <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
    <td><%= link_to 'Visualizar', qualificacao %></td>
    <td><%= link_to 'Editar', edit_qualificacao_path(qualificacao) %></td>
    <td><%= link_to 'Apagar', qualificacao, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
  </tr>
<% end %>
</table>

app/views/qualificacoes/new.html.erb
<h1>Nova Qualificacao</h1>

<%= render 'form' %>

<%= link_to 'Voltar', qualificacoes_path %>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.nome %>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p>



  <% unless @qualificacao.comentarios.empty?%>
	<%= comentarios @qualificacao %>
  <% end %>
  
  <%= novo_comentario(@qualificacao) %>
<%= link_to 'Editar', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Voltar', qualificacoes_path %>